# Generated by Django 4.2.27 on 2025-12-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Kategori premium (butuh paket berbayar)'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('FREE', 'Gratis'), ('BASIC', 'Paket Basic - Rp 10.000'), ('PREMIUM', 'Paket Premium - Rp 50.000')], default='FREE', max_length=10)),
                ('max_attempts_per_quiz', models.IntegerField(default=999)),
                ('max_categories', models.IntegerField(default=999)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
