# Generated by Django 4.2.27 on 2025-12-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizattempt_options_category_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='max_attempts_per_quiz',
            field=models.IntegerField(default=1),
        ),
    ]
