# Generated by Django 4.2.27 on 2026-04-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='preferred_timer_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='prefers_timer',
            field=models.BooleanField(default=False),
        ),
    ]
