# Generated by Django 4.2.27 on 2026-04-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_subscription_timer_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                help_text='Kosongkan jika ini adalah kategori utama.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subcategories',
                to='quiz.category',
            ),
        ),
    ]
