# Generated by Django 4.2.27 on 2026-04-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_explanation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'ordering': ['parent__name', 'name', 'id'],
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
